ARG ALPINE_VERSION
ARG PHP_VERSION
ARG VERSION

FROM hooklife/php-docker:php-fpm-nginx-${PHP_VERSION}-${ALPINE_VERSION}-${VERSION}
RUN echo '*  *  *  *  * /usr/local/bin/php  /app/artisan schedule:run >> /dev/null 2>&1' > /etc/crontabs/root

COPY config/supervisord/conf.d/horizon.conf /etc/supervisor/conf.d/
COPY config/supervisord/conf.d/crontab.conf /etc/supervisor/conf.d/

EXPOSE 80
CMD ["/usr/local/bin/supervisord"]